var hierarchy =
[
    [ "AssetManager", "classleia_1_1_asset_manager.html", null ],
    [ "AssetManagerBuffer", "classleia_1_1_asset_manager_buffer.html", null ],
    [ "Core", "classleia_1_1sdk_1_1_core.html", null ],
    [ "CoreInitConfiguration", "classleia_1_1sdk_1_1_core_init_configuration.html", null ],
    [ "EventListener", "classleia_1_1_event_listener.html", null ],
    [ "Interlacer", "classleia_1_1sdk_1_1_interlacer.html", [
      [ "InterlacerD3D11", "classleia_1_1sdk_1_1_interlacer_d3_d11.html", null ],
      [ "InterlacerD3D12", "classleia_1_1sdk_1_1_interlacer_d3_d12.html", null ],
      [ "InterlacerOpenGL", "classleia_1_1sdk_1_1_interlacer_open_g_l.html", null ],
      [ "InterlacerVulkan", "classleia_1_1sdk_1_1_interlacer_vulkan.html", null ]
    ] ],
    [ "InterlacerInitConfiguration", "classleia_1_1sdk_1_1_interlacer_init_configuration.html", null ],
    [ "leia_asset_manager_buffer", "structleia__asset__manager__buffer.html", null ],
    [ "leia_asset_manager_resolve_context", "structleia__asset__manager__resolve__context.html", null ],
    [ "leia_camera_intrinsics", "structleia__camera__intrinsics.html", null ],
    [ "leia_const_float_slice", "structleia__const__float__slice.html", null ],
    [ "leia_core", "structleia__core.html", null ],
    [ "leia_core_init_configuration", "structleia__core__init__configuration.html", null ],
    [ "leia_device_config", "structleia__device__config.html", null ],
    [ "leia_event", "structleia__event.html", null ],
    [ "leia_event_component", "structleia__event__component.html", null ],
    [ "leia_event_error", "structleia__event__error.html", null ],
    [ "leia_event_log", "structleia__event__log.html", null ],
    [ "leia_face_detector_config", "structleia__face__detector__config.html", null ],
    [ "leia_float_slice", "structleia__float__slice.html", null ],
    [ "leia_headtracking_detected_face", "structleia__headtracking__detected__face.html", null ],
    [ "leia_headtracking_detected_face_eye", "structleia__headtracking__detected__face__eye.html", null ],
    [ "leia_headtracking_detected_faces", "structleia__headtracking__detected__faces.html", null ],
    [ "leia_headtracking_face", "structleia__headtracking__face.html", null ],
    [ "leia_headtracking_frame_listener", "structleia__headtracking__frame__listener.html", null ],
    [ "leia_headtracking_frame_profiling", "structleia__headtracking__frame__profiling.html", null ],
    [ "leia_headtracking_moving_point", "structleia__headtracking__moving__point.html", null ],
    [ "leia_headtracking_raw_face", "structleia__headtracking__raw__face.html", null ],
    [ "leia_headtracking_raw_faces", "structleia__headtracking__raw__faces.html", null ],
    [ "leia_headtracking_tracking_result", "structleia__headtracking__tracking__result.html", null ],
    [ "leia_image_desc", "structleia__image__desc.html", null ],
    [ "leia_interlacer", "structleia__interlacer.html", null ],
    [ "leia_interlacer_debug_menu_configuration", "structleia__interlacer__debug__menu__configuration.html", null ],
    [ "leia_interlacer_gui_configuration", "structleia__interlacer__gui__configuration.html", null ],
    [ "leia_interlacer_gui_input_state", "structleia__interlacer__gui__input__state.html", null ],
    [ "leia_interlacer_init_configuration", "structleia__interlacer__init__configuration.html", null ],
    [ "leia_interlacer_single_view_mode_listener", "structleia__interlacer__single__view__mode__listener.html", null ],
    [ "leia_mat4", "structleia__mat4.html", null ],
    [ "leia_slice", "structleia__slice.html", null ],
    [ "leia_source_location", "structleia__source__location.html", null ],
    [ "leia_timestamp", "structleia__timestamp.html", null ],
    [ "leia_vector2d", "structleia__vector2d.html", null ],
    [ "leia_vector3", "structleia__vector3.html", null ],
    [ "leia_vector4", "structleia__vector4.html", null ]
];